import type { AppProps } from "next/app";
import Head from "next/head";
import React, { useState } from "react";
import { QueryClient, QueryClientProvider } from "react-query";
import "../styles/buttons.css";
import "../styles/colors.css";
import "../styles/fonts.css";
import "../styles/globals.css";
import "../styles/inputs.css";
import "../styles/texts.css";
import { LoginContext } from "../config/context";

function MyApp({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient()
  const [token, setToken] = useState('');

  return (
    <QueryClientProvider client={queryClient}>
      <LoginContext.Provider value={{ token, setToken}}>
        <Head>
          <title>Next Challenge</title>
          <meta
            name="description"
            content="Challenge to Next Js generated by create next app"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </LoginContext.Provider>
      </QueryClientProvider>
  );
}

export default MyApp;
