import type { AppProps } from "next/app";
import Head from "next/head";
import "../styles/buttons.css";
import "../styles/colors.css";
import "../styles/fonts.css";
import "../styles/globals.css";
import "../styles/inputs.css";
import "../styles/texts.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next Challenge</title>
        <meta
          name="description"
          content="Challenge to Next Js generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
