import type { NextPage } from 'next';
import clsx from 'clsx';
import Head from 'next/head';
import styles from '../styles/onboarding.module.css';

const Onboarding: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Challenge</title>
        <meta name="description" content="Challenge to Next Js generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={clsx('h1', styles.title)}>
          A tomar !
        </h1>
        <p className={clsx('body-i', styles.description)}>
          Registrate para poder jugar
        </p>
        <a href="screens/Login/" className={clsx('button buttonPrimary', styles.buttonLogin)}>
          Iniciar sesión
        </a>
        <a href="#" className={clsx('button buttonTertiary')}>
          Registrarse
        </a>
      </main>
    </div>
  )
}

export default Onboarding;
